#!/usr/bin/python
# SPDX-License-Identifier: MIT

import click
from extractors import extract
from cli import add, strip_markdown


@click.group()
def cli():
    pass


cli.add_command(extract)
cli.add_command(add)
cli.add_command(strip_markdown)

if __name__ == "__main__":
    cli()
